### PR TITLE
0.7.0 Release -> dev

### PR DESCRIPTION
**Pull request by chobobobo**
Merge master back into dev after release, I based this off dev, merged master into it and then resolved conflicts.

### CODE REVIEW

**Comment by chobobobo** [comment]
ah, there's still an issue with this merge, seeing
```
Creep worker-3200-3TypeError: structureMatrix.clone is not a function
    at Room.getCreepMatrix (room:933:43)
    at Object.getCreepMatrix (traveler:379:46)
    at Traveler.getCreepMatrix (traveler:316:56)
    at callback (traveler:131:35)
    at /app/node_modules/@screeps/driver/lib/path-finder.js:125:31
    at Object.exports.search (/app/node_modules/@screeps/driver/lib/path-finder.js:137:19)
    at Object. (/app/node_modules/@screeps/engine/dist/game/path-finder.js:54:38)
    at Object.search (evalmachine.:1:72)
    at Traveler.findTravelPath (traveler:138:36)
    at Traveler.travelTo (traveler:222:32)
```

**Comment by chobobobo** [comment]
Ok, it was a bad merge that had merged in some old code because it was reordered for some reason.  SourceTree is not letting me rebase it to squash the commits for whatever reason so this should be squash merged.

I've run this branch on a private server for sanity.
